site_name: NAP Reference Architecture
repo_url: https://github.com/NAPCORE/NAP-Reference-Architecture
site_url: https://napcore.github.io/NAP-Reference-Architecture/
repo_name: NAP-Reference-Architecture
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - Home: index.md
  - "The FRAME Architecture": frame.md
  - "NAP Reference Architecture": nap_architecture.md
  - Browsable UML Models:
      - FRAME Repository: uml/frame_repository.md
      - FRAME Meta Model: uml/frame_metamodel.md
      - NAP Reference Architecture: uml/nap_architecture.md
  - About: about.md

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - macros
