site_name: NAP Reference Architecture
repo_url: https://github.com/vlcinsky/mkdocs4frame
site_url: https://vlcinsky.github.io/mkdocs4frame/
repo_name: mkdocs4frame
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - Home: index.md
  - "The FRAME Architecture": frame.md
  - "NAP Reference Architecture": nap_architecture.md
  - Browsable UML Models:
      - FRAME Repository: uml/frame_repository.md
      - FRAME Meta Model: uml/frame_metamodel.md
      - NAP Reference Architecture: uml/nap_architecture.md
  - Feedback: feedback.md
  - About: about.md

markdown_extensions:
  - def_list
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - macros
