name: Tagged Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v2.1.0

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "version=$TAG" >> $GITHUB_OUTPUT

      - name: Rename model file to NRA.qea
        run: |
          MODEL_DIR="drafts/next/model"
          ORIGINAL=$(find "$MODEL_DIR" -type f -name '*.qea' | head -n 1)
          if [ -n "$ORIGINAL" ] && [ "$(basename "$ORIGINAL")" != "NRA.qea" ]; then
            mv "$ORIGINAL" "$MODEL_DIR/NRA.qea"
            echo "Renamed $ORIGINAL to NRA.qea"
          else
            echo "Model file already named correctly or not found."
          fi

      - name: Copy draft to release folder
        run: |
          VERSION=${{ steps.version.outputs.version }}
          mkdir -p "releases/$VERSION"
          cp -r drafts/next/* "releases/$VERSION/"
          rm -rf releases/latest
          cp -r "releases/$VERSION" releases/latest

      - name: Commit release folder
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add releases/
          git commit -m "Release ${{ steps.version.outputs.version }} and update latest"
          git push origin HEAD:main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          name: "Release v${{ steps.version.outputs.version }}"
          body: "Automated release for version v${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
