name: Update Latest Folder

on:
  release:
    types: [published]

jobs:
  update-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy new release to latest
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "Updating 'latest' to release $VERSION"

          # Clean up existing 'latest' folder
          rm -rf latest

          # Copy contents from version folder to 'latest'
          cp -r "$VERSION" latest

          # Commit and push changes
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add latest
          git commit -m "Update 'latest' to match $VERSION"
          git push
